services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  spark-master:
    image: spark:3.5.7
    container_name: spark-master
    hostname: spark-master
    command: >
      bash -c "mkdir -p /tmp/.ivy2/cache /tmp/.ivy2/jars && /opt/spark/sbin/start-master.sh && tail -f /dev/null"
    environment:
      HOME: /tmp
      SPARK_SUBMIT_OPTS: -Divy.cache.dir=/tmp/.ivy2/cache -Divy.home=/tmp/.ivy2
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/opt/spark-data
      - ./spark:/opt/spark-apps

  spark-worker:
    image: spark:3.5.7
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    command: >
      bash -c "mkdir -p /tmp/.ivy2/cache /tmp/.ivy2/jars && /opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    environment:
      HOME: /tmp
      SPARK_SUBMIT_OPTS: -Divy.cache.dir=/tmp/.ivy2/cache -Divy.home=/tmp/.ivy2
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
    ports:
      - "8081:8081"
    volumes:
      - ./data:/opt/spark-data
      - ./spark:/opt/spark-apps

  postgis:
    image: postgis/postgis:16-3.5
    container_name: postgis
    environment:
      POSTGRES_DB: mobility
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - ./postgis/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data: